#!/bin/sh

docker-compose run app black . -l 128; bs=$?

if [[ $bs -eq 0 ]] && [[ iss -eq 0 ]]
then
    git add .
else
    echo
    echo "There were problems formatting files."
    echo "Please fix the problems before committing."
    echo
    exit 1
fi