# Generated by Django 2.2.3 on 2019-08-15 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=60, unique=True)),
                ("name", models.TextField(max_length=60)),
                (
                    "body",
                    models.TextField(
                        help_text="Template to be rendered using Django template engine. Will receive a User object, a Unit object, and any fields that have been configured."
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentField",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.TextField()),
                ("required", models.BooleanField()),
                (
                    "field_type",
                    models.CharField(
                        choices=[("date", "date"), ("integer", "integer"), ("text", "text")], default="text", max_length=10
                    ),
                ),
                ("document", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="documents.Document")),
            ],
            options={"unique_together": {("name", "document")}},
        ),
    ]
