# Generated by Django 2.2.3 on 2019-08-15 00:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="DocumentTemplate",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField()),
                (
                    "body",
                    models.TextField(
                        help_text="Template to be rendered using Django template engine. Will receive a User object, a Unit object, and any fields that have been configured."
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="documentfield",
            name="document",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="documents.DocumentTemplate"),
        ),
        migrations.AlterField(model_name="documentfield", name="name", field=models.CharField(max_length=50)),
        migrations.DeleteModel(name="Document"),
    ]
