# Generated by Django 2.2.4 on 2019-08-20 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0003_auto_20190820_2200")]

    operations = [
        migrations.AddField(model_name="documentfield", name="name_en", field=models.CharField(max_length=50, null=True))
    ]
