# Generated by Django 2.2.4 on 2019-08-22 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0004_documentfield_name_en")]

    operations = [
        migrations.AlterField(
            model_name="documentfield",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="document_fields", to="documents.DocumentTemplate"
            ),
        )
    ]
