# Generated by Django 3.0.2 on 2020-01-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0006_auto_20191013_1956")]

    operations = [
        migrations.AddField(
            model_name="documenttemplate", name="include_on_get_started", field=models.BooleanField(default=False)
        )
    ]
