# Generated by Django 3.0.2 on 2020-01-16 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("documents", "0007_documenttemplate_include_on_get_started")]

    operations = [
        migrations.AddField(model_name="documentfield", name="name_es", field=models.CharField(max_length=50, null=True)),
        migrations.AddField(
            model_name="documenttemplate",
            name="description_es",
            field=models.TextField(
                blank=True, help_text="A description of the document. This will be shown to users.", null=True
            ),
        ),
        migrations.AddField(model_name="documenttemplate", name="name_es", field=models.CharField(max_length=50, null=True)),
    ]
