services:
  db:
    image: postgis/postgis:13-3.1-alpine
    environment:
      POSTGRES_DB: renters_rights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - main
  app:
    stdin_open: true
    tty: true
    build:
      context: .
      args:
        pipenv_arg: --dev
    environment:
      - DJANGO_SETTINGS_MODULE=renters_rights.settings.local
      - PYTHONUNBUFFERED=1
    volumes:
      - ./renters_rights:/app
    networks:
      - main
    depends_on:
      - db
      - s3
    ports:
      - "80:80"
  s3:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    networks:
      - main
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data

networks:
  main: