services:
  webpack:
    build:
      context: .
      target: webpack
      args:
        - "NODE_ENV=${NODE_ENV:-development}"
    command: bash -c "yarn run build && yarn run watch"
    depends_on:
      - app
    restart: "${DOCKER_RESTART_POLICY:-unless-stopped}"
    stop_grace_period: 3s
    tty: true
    environment:
      - NODE_ENV=development
    volumes:
      - ./renters_rights:/app
