# Generated by Django 2.2.3 on 2019-07-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("units", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="unitimage", name="unit"),
        migrations.AddField(
            model_name="unit", name="documents", field=models.ManyToManyField(related_name="documents", to="units.UnitImage")
        ),
        migrations.AddField(
            model_name="unit", name="images", field=models.ManyToManyField(related_name="images", to="units.UnitImage")
        ),
        migrations.AlterField(model_name="unit", name="lease_end_date", field=models.DateField(blank=True, null=True)),
        migrations.AlterField(model_name="unit", name="lease_start_date", field=models.DateField(blank=True, null=True)),
        migrations.AlterField(
            model_name="unit", name="rent_due_date", field=models.PositiveIntegerField(blank=True, null=True)
        ),
    ]
