# Generated by Django 2.2.3 on 2019-07-07 23:05

import localflavor.us.models
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("units", "0004_auto_20190707_1547")]

    operations = [
        migrations.AddField(model_name="unit", name="slug", field=models.SlugField(default="no"), preserve_default=False),
        migrations.AlterField(
            model_name="unit",
            name="landlord_address_1",
            field=models.CharField(blank=True, max_length=100, verbose_name="Landlord Address 1"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="landlord_address_2",
            field=models.CharField(blank=True, max_length=100, verbose_name="Landlord Address 2"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="landlord_city",
            field=models.CharField(blank=True, max_length=100, verbose_name="Landlord City"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="landlord_phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Landlord Phone Number"
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="landlord_state",
            field=localflavor.us.models.USStateField(blank=True, max_length=2, verbose_name="Landlord State"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="landlord_zip_code",
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, verbose_name="Landlord ZIP Code"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="lease_end_date",
            field=models.DateField(blank=True, null=True, verbose_name="Lease Start End Date"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="lease_start_date",
            field=models.DateField(blank=True, null=True, verbose_name="Lease Start Start Date"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="rent_due_date",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Day Rent Date"),
        ),
        migrations.AlterField(
            model_name="unit", name="unit_address_1", field=models.CharField(max_length=100, verbose_name="Unit Address 1")
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_address_2",
            field=models.CharField(blank=True, max_length=100, verbose_name="Unit Address 2"),
        ),
        migrations.AlterField(
            model_name="unit", name="unit_city", field=models.CharField(blank=True, max_length=100, verbose_name="Unit City")
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_state",
            field=localflavor.us.models.USStateField(blank=True, max_length=2, verbose_name="Unit State"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_zip_code",
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, verbose_name="Unit ZIP Code"),
        ),
    ]
