# Generated by Django 2.2.3 on 2019-07-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("units", "0005_auto_20190707_2305")]

    operations = [migrations.AlterField(model_name="unit", name="slug", field=models.SlugField(max_length=60, unique=True))]
