# Generated by Django 2.2.3 on 2019-07-21 21:00

import s3direct.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("units", "0006_auto_20190709_1358")]

    operations = [migrations.AlterField(model_name="unitimage", name="image", field=s3direct.fields.S3DirectField())]
