# Generated by Django 2.2.3 on 2019-08-15 00:16

from django.db import migrations, models

import units.models


class Migration(migrations.Migration):

    dependencies = [("units", "0007_auto_20190721_2100")]

    operations = [
        migrations.AlterField(
            model_name="unitimage", name="image", field=models.ImageField(upload_to=units.models.generate_file_path)
        )
    ]
