# Generated by Django 2.2.4 on 2019-08-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("units", "0008_auto_20190815_0016")]

    operations = [
        migrations.AddField(
            model_name="unit",
            name="landlord_name",
            field=models.CharField(blank=True, max_length=100, verbose_name="Landlord Name"),
        )
    ]
