# Generated by Django 2.2.6 on 2019-10-20 19:16

import localflavor.us.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("units", "0011_auto_20191003_0149")]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="unit_state",
            field=localflavor.us.models.USStateField(max_length=2, verbose_name="Unit State"),
        ),
        migrations.AlterField(
            model_name="unit",
            name="unit_zip_code",
            field=localflavor.us.models.USZipCodeField(max_length=10, verbose_name="Unit ZIP Code"),
        ),
    ]
