# Generated by Django 3.0.2 on 2020-01-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("units", "0012_auto_20191020_1916")]

    operations = [
        migrations.AlterField(
            model_name="unit",
            name="rent_due_date",
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name="Day Rent Due"),
        )
    ]
