# Generated by Django 2.2.3 on 2019-07-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("noauth", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="authcode",
            name="next_page",
            field=models.TextField(blank=True, default="/", editable=False, null=True),
        )
    ]
