# Generated by Django 2.2.6 on 2019-10-25 21:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("noauth", "0002_auto_20191003_0149")]

    operations = [
        migrations.AddField(
            model_name="authcode",
            name="previous_emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.EmailField(max_length=254), default=[], size=None
            ),
        )
    ]
