# Generated by Django 3.2.4 on 2021-06-12 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("noauth", "0005_auto_20191026_2217")]

    operations = [
        migrations.AlterField(
            model_name="user", name="first_name", field=models.CharField(blank=True, max_length=150, verbose_name="first name")
        )
    ]
