# Generated by Django 3.2.4 on 2021-07-01 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("noauth", "0006_alter_user_first_name")]

    operations = [
        migrations.RemoveField(model_name="user", name="code_last_sent"),
        migrations.RemoveField(model_name="user", name="pending_code"),
        migrations.RemoveField(model_name="user", name="pending_code_timestamp"),
        migrations.RemoveField(model_name="user", name="pending_new_email"),
        migrations.RemoveField(model_name="user", name="previous_emails"),
        migrations.DeleteModel(name="AuthCode"),
    ]
