# Generated by Django 3.2.4 on 2021-06-15 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuleGroup",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Rule",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("ordinance", models.CharField(max_length=25)),
                ("slug", models.SlugField(unique=True)),
                ("title", models.CharField(max_length=255)),
                ("title_es", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("plain_description", models.TextField(blank=True, null=True)),
                ("plain_description_es", models.TextField(blank=True, null=True)),
                ("plain_description_en", models.TextField(blank=True, null=True)),
                ("legal_description", models.TextField()),
                ("legal_description_es", models.TextField(null=True)),
                ("legal_description_en", models.TextField(null=True)),
                ("url", models.URLField()),
                ("rule_group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="rules.rulegroup")),
            ],
            options={"abstract": False},
        ),
    ]
