# Generated by Django 3.2.4 on 2021-06-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rules", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Ordinance",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("ordinance", models.CharField(max_length=25)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(
            model_name="rule",
            name="ordinance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="ordinance", to="rules.rulegroup"
            ),
        ),
        migrations.AlterField(
            model_name="rule",
            name="rule_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rule_group", to="rules.rulegroup"
            ),
        ),
    ]
