# Generated by Django 3.2.4 on 2021-06-16 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rules", "0003_auto_20210615_2256")]

    operations = [
        migrations.RemoveField(model_name="rule", name="legal_description"),
        migrations.RemoveField(model_name="rule", name="legal_description_en"),
        migrations.RemoveField(model_name="rule", name="legal_description_es"),
        migrations.AddField(
            model_name="ordinance", name="legal_description", field=models.TextField(default=" "), preserve_default=False
        ),
        migrations.AddField(model_name="ordinance", name="legal_description_en", field=models.TextField(null=True)),
        migrations.AddField(model_name="ordinance", name="legal_description_es", field=models.TextField(null=True)),
    ]
