# Generated by Django 3.2.4 on 2021-06-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("rules", "0005_auto_20210616_0115")]

    operations = [
        migrations.AddField(
            model_name="ordinance", name="title", field=models.CharField(default="TODO", max_length=255), preserve_default=False
        )
    ]
